site_name: AlmaLinux Mirror Propagation Report
copyright: Copyright &copy; 2000 - 2024 rodrigo de avila
repo_name: rdeavila/almalinux-mirrors-report
theme:
  name: material
  language: en
  logo: https://wiki.almalinux.org/images/logo.png
  favicon: https://almalinux.org/fav/favicon-32x32.png
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rdeavila/almalinux-mirrors-report
