name: Create Report

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  create_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Calculate mirror drift
        run: |
          bash run.sh
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material  mkdocs-minify-plugin
      - name: Compile HTML file
        run: |
          mkdocs build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b3e2c8cc31d84afe192b6a5353c2f7ef
          projectName: almalinux-mirrors-report
          directory: site
          branch: main
