name: Create Report

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:


jobs:
  create_report:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq python3-pip curl
          pip install yq mkdocs-material mkdocs-minify-plugin
      - name: Calculate mirror drift
        run: |
          which mkdocs
          bash run.sh > docs/index.md
      - name: Compile HTML file
        run: |
          mkdocs build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b3e2c8cc31d84afe192b6a5353c2f7ef
          projectName: almalinux-mirrors-report
          directory: site
          branch: main
