name: Create Report

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  create_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Calculate mirror drift
        run: |
          bash run.sh
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: b3e2c8cc31d84afe192b6a5353c2f7ef
          projectName: almalinux-mirrors-report
          directory: site
          branch: main
